### ISSUE TITLE
Update GitLab OIDC to SAML by default

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-gitlab#102]
### Is your feature request related to a problem? Please describe.
As Ezra I want SAML to be the default GitLab auth so that I can have a more secure default for larger environments.

### Describe the solution you'd like

- **Given** I specify SSO to be on within the GitLab package
- **And** provide no additional bundle overrides
- **When** I deploy the package to the cluster
- **Then** GitLab will be configured to connect to Keycloak over SAML.

### Describe alternatives you've considered
We could leave it as is with OIDC but this is less secure: https://github.com/defenseunicorns/uds-package-gitlab/blob/main/adr/0002-keycloak-integration.md#decision

### Additional context
This should minimize breakage for consumers - an option to keep OIDC for those that have / want it should be considered.

**Comment by Racer159** [comment]
When doing this we should normalize this package with helm best practices and the new sonarqube package's way of doing things - namely providing consistent values keys for sso configuration (i.e. `sso.enabled`)

**Comment by Racer159** [comment]
Ignore that previous comment - this is being done here: https://github.com/defenseunicorns/uds-package-gitlab/pull/115

**Comment by Racer159** [comment]
Normalization should still happen though where we still need to do it though

**Comment by ericwyles** [comment]
Need this PR merged and a new release of uds-core to finish testing. https://github.com/defenseunicorns/uds-identity-config/pull/77
