### ISSUE TITLE
 Add Journey Testing for GitLab

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-gitlab#130]
### Describe what should be investigated or refactored
We need to implement journey testing for our applications so that we can have assurance that things are still functional when changes are made to our applications.  For GitLab we should test the following to ensure our integrations are working:

1. Sign-in through SSO (Keycloak)
2. Creating a repo (Database / Gitaly)
2. Navigate to a file / api with `%2F` in the URL (Istio)
3. Upload a file (Object Storage)

### Links to any relevant code
This imported task will likely be useful for setup:
https://github.com/defenseunicorns/uds-common/blob/b2e8b25930c953ef893e7c787fe350f0d8679ee2/tasks/setup.yaml#L33

### Additional context
This should be laid out in a way we can port similar naming conventions / patterns across our applications.

**Comment by marshall007** [comment]
@Racer159 do you have an example of  (3) `Navigate to a file / api with %2F in the URL`? I know I have seen that happen myself, but in poking around today I wasn't able to find a case where that happens.

**Comment by Racer159** [comment]
Here is the issue we ran into: https://github.com/defenseunicorns/uds-core/issues/288 - I think the simplest is the namespace%2Fproject endpoints in the API
