### ISSUE TITLE
Implement a secret generation function to setup object storage

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-package-gitlab#146]
## Is your feature request related to a problem? Please describe.
As Ezra I want a way to manually setup the S3 configuration directly with the config chart so that I do not need to manage a package out of band in a bundle for this.

## Describe the solution you'd like
* Given I have the following for an S3 connection:
    * `ENDPOINT`
    * `ACCESS_KEY`
    * `ACCESS_KEY_SECRET`
    * `BUCKET_PREFIX`
    * `BUCKET_SUFFIX`
* When I provide these under the appropriate key (`objectStorage.s3`) to the config chart
* Then the config chart generates the appropriate `gitlab-object-store` secret for this service with the appropriate format for an S3 API compliant object storage provider

## Describe alternatives you've considered
We could keep the status quo and change Mattermost to not have this pattern but this pattern is a nice to have when you need to manually provide a username / password.

Additional context
* This is similar to the pattern Mattermost uses and should be done similarly from a Helm values perspective: https://github.com/defenseunicorns/uds-package-mattermost/blob/fce7636395d1e3afab5fcf8a502c084bd21a8a83/chart/values.yaml#L12
* Relates to #145 
* The current pattern requires duplicating (or sharing) configuration at the bundle level so that the out-of-band secret can set the appropriate bucket name given the prefix/suffix vars.
* Generalizing the helm value to `objectStorage` at the top level leaves room for other secret implementations for other providers

**Comment by Racer159** [comment]
Note this should also be documented in the common SWF docs and each depending app's `configuration.md`
