### ISSUE TITLE
Ensure GitLab pages works

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-package-gitlab#15]
Likely need some work to make pages work.   

https://github.com/defenseunicorns/uds-package-gitlab/blob/main/values/gitlab-values.yaml#L129-L139

GL Pages should be working / enabled internally but aren't properly exposed through Istio.

**Comment by Racer159** [comment]
Pages is initially controlled via this var: https://github.com/defenseunicorns/uds-package-gitlab/blob/625fde509d048fe0ea22939f0b2151caf385cd94/zarf.yaml#L27

**Comment by Racer159** [comment]
https://github.com/defenseunicorns/uds-package-gitlab/blob/625fde509d048fe0ea22939f0b2151caf385cd94/values/common-values.yaml#L142 - updated link
