### ISSUE TITLE
Replace dev-redis package in the test bundle with uds-package-valkey

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-gitlab#150]
### Describe what should be investigated or refactored
Now that we have a uds package for [valkey](https://github.com/defenseunicorns/uds-package-valkey), we should replace the [dev-redis](https://github.com/defenseunicorns/uds-package-gitlab/blob/5d48380e57b40a66aa8000059f5f5caa1c6e7558/bundle/uds-bundle.yaml#L29) package being pulled into the bundle.

**Comment by Racer159** [comment]
We should test what happens when you go from a redis-based bundle to a valkey based one

**Comment by Racer159** [comment]
This should just work as long as no bg jobs are running but we should call this out as a potential gotcha
https://docs.gitlab.com/ee/administration/backup_restore/backup_gitlab.html#other-data

**Comment by Racer159** [comment]
While doing this should upgrade postgres to a newer version (17 adds support for later versions)
