### ISSUE TITLE
Cleanup the root `zarf.yaml` imports

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-gitlab#21]
There are a few things that could be cleaned up about the root `zarf.yaml` in this repo:

https://github.com/defenseunicorns/uds-package-gitlab/blob/main/zarf.yaml

1. Lines 42/43 are not needed - Zarf will always include all charts from the common child
2. A global `architecture` may be fine for your use case but it would prevent an upstream arm package from being made - using `only.cluster.architecture` only on the registry1 component would limit those effects to that flavor type
3. `description` can come from the common child package unless you want to override it with something specific
4. The yaml schema version can be in vscode settings to apply globally and be pinned to a specific Zarf version - https://github.com/defenseunicorns/uds-core/blob/main/.vscode/settings.json
5. The `renovate.json` can automatically update charts with something like https://github.com/defenseunicorns/zarf/blob/2319b6f9d5491ed7bac8b63322c030cac1d4ffe9/renovate.json#L47

**Comment by zachariahmiller** [comment]
Will be completed by https://github.com/defenseunicorns/uds-package-gitlab/pull/29
