### ISSUE TITLE
Update repo to utilize workflows, actions and tasks from the uds-common repo

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-gitlab#39]
### Describe what should be investigated or refactored
We created a repo to enable reuse of common uds tasks, gh actions and gh workflows. This repo should be updated to utilize the common ones where possible. 

### Links to any relevant code
https://github.com/defenseunicorns/uds-common

### Additional context
Any questions just ask.

**Comment by ericwyles** [comment]
I'm picking this one up.

**Comment by ericwyles** [comment]
@zachariahmiller I changed to the uds-common setup action, but that action is missing Zarf and node.js setup steps. Do you think we want to add those to the uds-common setup? (you can see in my draft PR CI is failing because Zarf is not found.)

**Comment by zachariahmiller** [comment]
@ericwyles FYSA Closing this issue because it is completed. I guess moving it to done on the board does not complete it. Usually my issues auto-complete when i merge the associated pr after I create them from the issue. Not immediately clear what was done differently here so that made that not work.

**Comment by ericwyles** [comment]
@zachariahmiller Thanks. I was thinking moving it on the board would close it. I'll try to notice next time if I missed an option on PR merge that should have closed it.
