### ISSUE TITLE
Research backup solution for GitLab

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-gitlab#50]
### Is your feature request related to a problem? Please describe.
**As** Ashton **I want** to be able to backup GitLab safely **so that** I can restore it easily in the event of a disaster.

### Describe the solution you'd like

We should identify and select solutions that are able to backup the variety of places that GitLab stores data:

https://docs.gitlab.com/ee/administration/backup_restore/backup_gitlab.html

And then follows the recommendations for restoring a GitLab server:

https://docs.gitlab.com/ee/administration/backup_restore/restore_gitlab.html

These should be written in a simple ADR to capture why the final solution was chosen and a follow on implementation issue should be created.

### Additional context

We currently don't have set SLAs but should target a baseline to have something while we continue to experiment.

**Comment by zachariahmiller** [comment]
High level: Follow practices [here](https://docs.gitlab.com/ee/administration/backup_restore/backup_large_reference_architectures.html) for services. Keep everything possible in aws provided storage (RDS, S3, Elasticache) Ideally manage secrets externally to mitigate risk and easy restore process. Implement functional equivalent or linux ec2 backup/restore steps on the k8s pods that they are analogous to.

**Comment by oates** [comment]
@oates add spike label

**Comment by Racer159** [comment]
We should sync with @corang as well since his team has started down this path already

**Comment by Racer159** [comment]
This may also help inform what we want to say for this issue: https://github.com/defenseunicorns/uds-common/issues/130

**Comment by oates** [comment]
🔫 this issue and opened this one https://github.com/defenseunicorns/uds-infrastructure/issues/600
