### ISSUE TITLE
Add flavor matrix for single package test.

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-gitlab#57]
### Describe what should be investigated or refactored
Currently the gitlab package is only being tested against the registry1 flavor. We would like to validate that both registry1 and upstream flavors work correctly in the individual package repos so we can better consolidate our testing in the full swf integration repo. Completing this issue will align the gitlab package testing to what already exists in the other SWF single package repos. 

### Links to any relevant code
See the MM test workflow for example https://github.com/defenseunicorns/uds-package-mattermost/blob/8f5d0ccff33edae72e02df88b3b49952eeb2b498/.github/workflows/test.yaml#L28

### Additional context

Generally speaking, any issues that are flavor specific should be able to be caught in single package tests as the differences are limited in this case to image refs and security contexts. The full SWF tests will be longer and more resrouce intensive so it is in our best interest to handle these specific tests at the package level.

**Comment by Racer159** [comment]
solved by #63
