### ISSUE TITLE
Update the config chart to template out the netpol generation section of the uds-package cr. 

### ISSUE THREAD

**Issue by zachariahmiller** [defenseunicorns/uds-package-gitlab#78]
Consumers of this package should be able to define fine grained netpols for egress. This will require adding some templating to the uds-package cr for communication that is not strictly internal. By default, the values should be locked down as much as possible but be able to be overriden to access certain endpoints (for example an external database).

https://github.com/defenseunicorns/uds-package-gitlab/pull/77#discussion_r1531238000

**Comment by zachariahmiller** [comment]
@blancharda for reference/tracking when the change happens

**Comment by Racer159** [comment]
As a follow on we should create tickets for Mattermost, SonarQube and GitLab Runner

**Comment by Racer159** [comment]
https://github.com/defenseunicorns/uds-core/tree/main/src/pepr/operator
