### ISSUE TITLE
Add templating to provide more specific network policies

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-package-gitlab#82]
### Overview
The [current network policy egress routes](https://github.com/defenseunicorns/uds-package-gitlab/blob/main/charts/config/templates/uds-package.yaml#L58-L106) allow for `remoteGenerated: Anywhere` on almost all gitlab pods. We should enable more restrictive egress policies by adding helm values and corresponding templates to allow a user to customize more limited egress for their specific environment. 

[See more discussion here](https://github.com/defenseunicorns/uds-package-gitlab/pull/77#discussion_r1531238000)

### Proposal
- Identify points of egress (database, storage, redis... other?) and map them to each gitlab pod
- Add individual egress rules for each mapping
- By default, perhaps we continue to allow traffic anywhere so that network policies don't break an initial install
- Template the destination to allow for a custom CIDR (once this is implemented) // pod selector + namespace // other destination?
- Consider something like `values.additionalNetworkAllows[]` to allow a user to specify fully custom additional rules

**Comment by blancharda** [comment]
Duplicates #78

**Comment by zachariahmiller** [comment]
@blancharda Appreciate you!
