### ISSUE TITLE
Replace the `dev-postgres` package with the `postgres-operator` 

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/uds-package-gitlab#96]
### Describe what should be investigated or refactored
We need to replace the dev-postgres package with the postgres-operator package so that we test and use a more prod-ready version during development.

### Links to any relevant code
https://github.com/defenseunicorns/uds-package-gitlab/blob/e0972cb936af9b13d3d1d58c058c97cf9f272160/bundle/uds-bundle.yaml#L14
https://github.com/defenseunicorns/uds-package-postgres-operator/

### Additional context
This postgres package will likely not be the main focus but we should ensure that it is reasonably well tested since it is currently trying to be used.

We should make sure this doesn't bump us to needing a higher spec runner (including leaving enough headroom for the gitlab runner)

**Comment by Racer159** [comment]
https://github.com/defenseunicorns/uds-software-factory/blob/bfd10ff3c519583989804d5d28e71b17e76f9628/bundles/dev/uds-bundle.yaml#L20

**Comment by zachariahmiller** [comment]
values corresponding to above link: https://github.com/defenseunicorns/uds-software-factory/blob/bfd10ff3c519583989804d5d28e71b17e76f9628/bundles/dev/uds-config.yaml#L3
